workflows:
  mac_mini_workflow:
    name: "Mac Mini M2 CI"
    max_build_duration: 40
    macos:
      xcode: latest
      image: mac-mini-m2
    environment:
      vars:
        CI: "true"
    scripts:
      - name: Install Google Chrome
        script: |
          brew install --cask google-chrome
      - name: Launch Terminal & Keep Alive
        script: |
          echo "Chrome installed. Keeping session alive..."
          tail -f /dev/null
