workflows:
  remotix-mac:
    name: Remotix on Mac Mini M2
    instance_type: mac_mini_m2
    max_build_duration: 40
    environment:
      vars:
        LC_ALL: "en_US.UTF-8"
        LANG: "en_US.UTF-8"

    scripts:

      - name: Keep Terminal Alive
        script: |
          echo "Remotix Agent started. Terminal will stay alive..."
          tail -f /dev/null
