workflows:
  remotix-mac:
    name: Remotix on Mac Mini M2
    instance_type: mac_mini_m2
    max_build_duration: 40
    environment:
      vars:
        LC_ALL: "en_US.UTF-8"
        LANG: "en_US.UTF-8"

    scripts:
      - name: Install Remotix Agent
        script: |
          brew install --cask remotix-agent

      - name: Start Remotix Agent
        script: |
          sudo /Applications/Remotix\ Agent.app/Contents/MacOS/RemotixAgent &

      - name: Keep Terminal Alive
        script: |
          echo "Remotix Agent started. Terminal will stay alive..."
          tail -f /dev/null
