workflows:
  mac_mini_workflow:
    name: Mac Mini M2 CI
    max_build_duration: 40          # số nguyên, phút
    instance_type: mac_mini_m2      # định nghĩa máy Mac
    environment:
      vars:
        CI: "true"
    scripts:
      - name: Install Google Chrome
        script: |
          brew install --cask google-chrome
      - name: Keep terminal alive
        script: |
          echo "Chrome installed. Keeping session alive..."
          tail -f /dev/null
